// Code generated by bartolo. DO NOT EDIT.
// See https://github.com/orq-ai/bartolo

package generated

import (
	"fmt"
	"strings"

	neturl "net/url"

	bartolocli "github.com/orq-ai/bartolo/cli"
	"github.com/pkg/errors"
	"github.com/spf13/viper"
	"gopkg.in/h2non/gentleman.v2"
)

func servers() []map[string]string {
	return []map[string]string{

		map[string]string{
			"description": "",
			"url":         "https://api.example.com",
		},
	}
}

func initGeneratedRuntime() {
	bartolocli.RegisterServers(servers())

}

// ExampleGetThing Get a thing
func ExampleGetThing(paramId string, paramFrom string, paramFromTime string, params *viper.Viper) (*gentleman.Response, interface{}, error) {
	handlerPath := "get-thing id from from-time"
	server := bartolocli.ResolveServer()

	url := server + "/{id}"
	if paramId == "" {
		return nil, nil, bartolocli.NewValueError(errors.Errorf("path parameter id cannot be empty"))
	}

	{
		normalized, err := bartolocli.NormalizeParam("argument id", paramId, "uuid", []string{})
		if err != nil {
			return nil, nil, err
		}
		paramId = normalized
	}
	{
		normalized, err := bartolocli.NormalizeParam("argument from", paramFrom, "date-time", []string{})
		if err != nil {
			return nil, nil, err
		}
		paramFrom = normalized
	}
	url = strings.Replace(url, "{id}", neturl.PathEscape(paramId), 1)

	req := bartolocli.Client.Get().URL(url)

	req = req.AddQuery("from", paramFrom)

	req = req.AddQuery("from-time", paramFromTime)

	paramDetailed := params.GetBool("detailed")
	if bartolocli.FlagPassed(params, "detailed") || paramDetailed != false {
		req = req.AddQuery("detailed", fmt.Sprintf("%v", paramDetailed))
	}
	paramLimit := params.GetInt64("limit")
	if bartolocli.FlagPassed(params, "limit") || paramLimit != 0 {
		req = req.AddQuery("limit", fmt.Sprintf("%v", paramLimit))
	}
	paramRatio := params.GetFloat64("ratio")
	if bartolocli.FlagPassed(params, "ratio") || paramRatio != 0.0 {
		req = req.AddQuery("ratio", fmt.Sprintf("%v", paramRatio))
	}
	paramKind := params.GetString("kind")
	if bartolocli.FlagPassed(params, "kind") || paramKind != "" {
		{
			normalized, err := bartolocli.NormalizeParam("--kind", paramKind, "", []string{"internal", "a2a"})
			if err != nil {
				return nil, nil, err
			}
			paramKind = normalized
		}
		req = req.AddQuery("kind", fmt.Sprintf("%v", paramKind))
	}
	paramTo := params.GetString("to")
	if bartolocli.FlagPassed(params, "to") || paramTo != "" {
		{
			normalized, err := bartolocli.NormalizeParam("--to", paramTo, "date-time", []string{})
			if err != nil {
				return nil, nil, err
			}
			paramTo = normalized
		}
		req = req.AddQuery("to", fmt.Sprintf("%v", paramTo))
	}
	paramCursor := params.GetString("cursor")
	if bartolocli.FlagPassed(params, "cursor") || paramCursor != "" {
		req = req.AddQuery("cursor", fmt.Sprintf("%v", paramCursor))
	}
	paramSess := params.GetString("sess")
	if bartolocli.FlagPassed(params, "sess") || paramSess != "" {
		{
			normalized, err := bartolocli.NormalizeParam("--sess", paramSess, "", []string{"a", "b"})
			if err != nil {
				return nil, nil, err
			}
			paramSess = normalized
		}
	}

	bartolocli.HandleBefore(handlerPath, params, req)

	resp, err := req.Do()
	if err != nil {
		return nil, nil, errors.Wrap(err, "request failed")
	}

	var decoded interface{}

	if resp.StatusCode < 400 {
		if err := bartolocli.UnmarshalResponse(resp, &decoded); err != nil {
			return nil, nil, errors.Wrap(err, "unmarshalling response failed")
		}
	} else {
		return nil, nil, bartolocli.ResponseError(resp)
	}

	after := bartolocli.HandleAfter(handlerPath, params, resp, decoded)
	if after != nil {
		decoded = after
	}

	return resp, decoded, nil
}

// ExampleCreateWidget Create a widget
func ExampleCreateWidget(params *viper.Viper, body string) (*gentleman.Response, map[string]interface{}, error) {
	handlerPath := "widgets create"
	server := bartolocli.ResolveServer()

	url := server + "/widgets"

	req := bartolocli.Client.Post().URL(url)

	if body != "" {
		req = req.AddHeader("Content-Type", "application/json").BodyString(body)
	}

	bartolocli.HandleBefore(handlerPath, params, req)

	resp, err := req.Do()
	if err != nil {
		return nil, nil, errors.Wrap(err, "request failed")
	}

	var decoded map[string]interface{}

	if resp.StatusCode < 400 {
		if err := bartolocli.UnmarshalResponse(resp, &decoded); err != nil {
			return nil, nil, errors.Wrap(err, "unmarshalling response failed")
		}
	} else {
		return nil, nil, bartolocli.ResponseError(resp)
	}

	after := bartolocli.HandleAfter(handlerPath, params, resp, decoded)
	if after != nil {
		decoded = after.(map[string]interface{})
	}

	return resp, decoded, nil
}

// ExampleDeleteWidget Delete a widget
func ExampleDeleteWidget(paramId string, params *viper.Viper) (*gentleman.Response, interface{}, error) {
	handlerPath := "widgets delete id"
	server := bartolocli.ResolveServer()

	url := server + "/widgets/{id}"
	if paramId == "" {
		return nil, nil, bartolocli.NewValueError(errors.Errorf("path parameter id cannot be empty"))
	}

	url = strings.Replace(url, "{id}", neturl.PathEscape(paramId), 1)

	req := bartolocli.Client.Delete().URL(url)

	bartolocli.HandleBefore(handlerPath, params, req)

	resp, err := req.Do()
	if err != nil {
		return nil, nil, errors.Wrap(err, "request failed")
	}

	var decoded interface{}

	if resp.StatusCode < 400 {
		if err := bartolocli.UnmarshalResponse(resp, &decoded); err != nil {
			return nil, nil, errors.Wrap(err, "unmarshalling response failed")
		}
	} else {
		return nil, nil, bartolocli.ResponseError(resp)
	}

	after := bartolocli.HandleAfter(handlerPath, params, resp, decoded)
	if after != nil {
		decoded = after
	}

	return resp, decoded, nil
}

// ExampleSearchWidgets Search widgets
func ExampleSearchWidgets(params *viper.Viper) (*gentleman.Response, map[string]interface{}, error) {
	handlerPath := "widgets search"
	server := bartolocli.ResolveServer()

	url := server + "/widgets/search"

	req := bartolocli.Client.Post().URL(url)

	bartolocli.HandleBefore(handlerPath, params, req)

	resp, err := req.Do()
	if err != nil {
		return nil, nil, errors.Wrap(err, "request failed")
	}

	var decoded map[string]interface{}

	if resp.StatusCode < 400 {
		if err := bartolocli.UnmarshalResponse(resp, &decoded); err != nil {
			return nil, nil, errors.Wrap(err, "unmarshalling response failed")
		}
	} else {
		return nil, nil, bartolocli.ResponseError(resp)
	}

	after := bartolocli.HandleAfter(handlerPath, params, resp, decoded)
	if after != nil {
		decoded = after.(map[string]interface{})
	}

	return resp, decoded, nil
}
