// Code generated by bartolo. DO NOT EDIT.
// See https://github.com/orq-ai/bartolo

package generated

import (
	bartolocli "github.com/orq-ai/bartolo/cli"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func registerwidgetsCommands(root *cobra.Command) {
	widgetsCmd := &cobra.Command{
		Use:   "widgets",
		Short: "Widgets",
		Long:  bartolocli.Markdown("Widgets"),
	}
	bartolocli.HelpSection(root, widgetsCmd, "Writes")
	root.AddCommand(widgetsCmd)

	func() {
		parent := widgetsCmd

		params := viper.New()

		var examples string

		examples += "  " + parent.CommandPath() + " create --example\n"

		cmd := &cobra.Command{
			Use:     "create",
			Short:   "Create a widget",
			Long:    bartolocli.Markdown("\n\nRequest body: `application/json`. Provide it via stdin or CLI shorthand.\nRun `help-input` for body syntax details.\n\nTop-level fields:\n- `created_after` (string)\n- `status` (string)\n\nAll top-level body fields are exposed as flags for this command. Scalar, nullable scalar (pass `null` for JSON null), enum, repeatable list (`--field a --field b`), and string map (`--field key=value`) fields use typed flags. Nested objects, arrays of objects, and polymorphic unions accept a JSON string (e.g. `--field '{\"k\":1}'`). Timestamp fields (`format: date-time`) also accept a bare date or a relative value such as `24h`, `7d` or `now-24h`."),
			Example: examples,
			Args:    cobra.MinimumNArgs(0),
			RunE: func(cmd *cobra.Command, args []string) error {

				bartolocli.MarkPassedFlags(cmd, params)
				if bartolocli.PrintBodyExample(params, "{\n  \"status\": \"active\"\n}") {
					return nil
				}
				body, err := bartolocli.GetBodyWithFlags(cmd, "application/json", args[0:], params,
					[]bartolocli.BodyField{
						{
							Name:        "created_after",
							FlagName:    "created-after",
							Type:        "datetime",
							Description: "",
						},
						{
							Name:        "status",
							FlagName:    "status",
							Type:        "enum-string",
							Description: "",
							Enum: []string{
								"active",
								"archived",
							},
						},
					},
				)
				if err != nil {
					return errors.Wrap(err, "unable to get body")
				}

				_, decoded, err := ExampleCreateWidget(params, body)
				if err != nil {
					return bartolocli.OperationError(err)
				}

				if err := bartolocli.Formatter.Format(decoded); err != nil {
					return errors.Wrap(err, "formatting failed")
				}

				return nil

			},
		}
		bartolocli.HelpSection(parent, cmd, "Writes")
		parent.AddCommand(cmd)
		bartolocli.AddBodyFlags(cmd)
		bartolocli.AddExampleFlag(cmd)
		bartolocli.AddBodyFieldFlags(cmd,
			[]bartolocli.BodyField{
				{
					Name:        "created_after",
					FlagName:    "created-after",
					Type:        "datetime",
					Description: "",
				},
				{
					Name:        "status",
					FlagName:    "status",
					Type:        "enum-string",
					Description: "",
					Enum: []string{
						"active",
						"archived",
					},
				},
			},
		)

		bartolocli.SetCustomFlags(cmd)

		if cmd.Flags().HasFlags() {
			params.BindPFlags(cmd.Flags())
		}

	}()

	func() {
		parent := widgetsCmd

		params := viper.New()

		var examples string

		cmd := &cobra.Command{
			Use:     "delete id",
			Short:   "Delete a widget",
			Long:    bartolocli.Markdown("Delete a widget\n\n## Arguments\n\n- `id`"),
			Example: examples,
			Args:    cobra.MinimumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {

				bartolocli.MarkPassedFlags(cmd, params)
				if err := bartolocli.ConfirmDestructive(cmd, args); err != nil {
					return err
				}

				_, decoded, err := ExampleDeleteWidget(args[0], params)
				if err != nil {
					return bartolocli.OperationError(err)
				}

				if err := bartolocli.Formatter.Format(decoded); err != nil {
					return errors.Wrap(err, "formatting failed")
				}

				return nil

			},
		}
		parent.AddCommand(cmd)
		bartolocli.AddForceFlag(cmd)

		bartolocli.SetCustomFlags(cmd)

		if cmd.Flags().HasFlags() {
			params.BindPFlags(cmd.Flags())
		}

	}()

}
