// Code generated by bartolo. DO NOT EDIT.
// See https://github.com/orq-ai/bartolo

package generated

import (
	bartolocli "github.com/orq-ai/bartolo/cli"
	"github.com/pkg/errors"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

func registerRootCommands(root *cobra.Command) {

	func() {
		parent := root

		params := viper.New()

		var examples string

		cmd := &cobra.Command{
			Use:     "get-thing id",
			Short:   "Get a thing",
			Long:    bartolocli.Markdown(""),
			Example: examples,
			Args:    cobra.MinimumNArgs(1),
			RunE: func(cmd *cobra.Command, args []string) error {

				bartolocli.MarkPassedFlags(cmd, params)

				_, decoded, err := ExampleGetThing(args[0], params)
				if err != nil {
					return bartolocli.OperationError(err)
				}

				if err := bartolocli.Formatter.Format(decoded); err != nil {
					return errors.Wrap(err, "formatting failed")
				}

				return nil

			},
		}
		parent.AddCommand(cmd)

		cmd.Flags().Bool("detailed", false, "")
		cmd.Flags().Int64("limit", 0, "")
		cmd.Flags().Float64("ratio", 0.0, "")
		cmd.Flags().String("kind", "", " (one of: internal, a2a)")
		_ = cmd.RegisterFlagCompletionFunc("kind", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return []string{"internal", "a2a"}, cobra.ShellCompDirectiveNoFileComp
		})
		cmd.Flags().String("cursor", "", "")
		cmd.Flags().String("sess", "", " (one of: a, b)")
		_ = cmd.RegisterFlagCompletionFunc("sess", func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return []string{"a", "b"}, cobra.ShellCompDirectiveNoFileComp
		})

		bartolocli.SetCustomFlags(cmd)

		if cmd.Flags().HasFlags() {
			params.BindPFlags(cmd.Flags())
		}

	}()

}
